spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chimhaha?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: hmlim1004^^
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  # make color in console
  output:
    ansi:
      enabled: always

  # file upload system

logging:
  level:
    org:
      hibernate:
        SQL: debug
      apache:
        coyote:
          http11: debug

#  org.hibernate.type: trace

file:
  dir: /Users/hyunmooklim/Desktop/imageFiles/